function showMessage(message,callback){
//     setTimeout(()=>{
//         console.log(message);
//         callback();
//     },2000)
// }
// showMessage("Loading...",()=>{
//     console.log("Finished")
// })
// showMessage("Hello");